# Step 1: Build React app
FROM node:20

WORKDIR /app

ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_API_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./

RUN npm install

COPY . .

# Step 2: Serve with Nginx

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
