# FROM node:20-alpine

# WORKDIR /app
# COPY src ./src

# COPY package*.json ./

# RUN npm install

# EXPOSE 4000

# CMD ["npm", "run", "devStart"]
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY src ./src
COPY database ./database
COPY node-pg-migrate.config.js ./

EXPOSE 4000

CMD ["npm", "run", "devStart"]

